
# aws

spring:
    datasource:
      url: jdbc:mariadb://mydatabase.c4h89kt7p5q1.ap-northeast-2.rds.amazonaws.com/mydatabase
      driverClassName: org.mariadb.jdbc.Driver
      username: demoproject
      password: demodemo22
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create
    
# local mariadb

#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/mariadb
#    driverClassName: org.mariadb.jdbc.Driver
#    username: root
#    password: root
#  jpa:
#    open-in-view: false
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#     ddl-auto: create 
    
        # show-sql: true
        # properties:
        #    hibernate:
        #        format_sql: true

